#!/bin/bash

PANNICC_DIR="${HOME}/code/projects/PANNICC"

PANNICC="${PANNICC_DIR}/build/bin/pannicc"
INPUT_DIR="${PANNICC_DIR}/test/regression/input"
OUTPUT_DIR="${PANNICC_DIR}/test/regression/expected"

for test in ${INPUT_DIR}/*.c; do
    BASE_NAME=$(basename ${test})
    echo "Updating output for ${BASE_NAME}..."

    INPUT="${BASE_NAME%.c}"

    $(${PANNICC} --dump-ast ${test} > ${OUTPUT_DIR}/${INPUT}.ast)
    $(${PANNICC} --dump-hir ${test} > ${OUTPUT_DIR}/${INPUT}.hir)

    $(${PANNICC} --dump-mir -O0 ${test} > ${OUTPUT_DIR}/${INPUT}_o0.mir)
    $(${PANNICC} --dump-mir -O1 ${test} > ${OUTPUT_DIR}/${INPUT}_o1.mir)

    $(${PANNICC} -O0 ${test} > ${OUTPUT_DIR}/${INPUT}_o0.lir)
    $(${PANNICC} -O1 ${test} > ${OUTPUT_DIR}/${INPUT}_o1.lir)

    PASSES=${INPUT_DIR}/${INPUT}.passes
    if [ -e ${PASSES} ]; then
        PARAMS=$(paste -sd, ${PASSES})
        $(${PANNICC} --dump-mir -O0 --passes=${PARAMS} ${test} > ${OUTPUT_DIR}/${INPUT}_select.mir)
        $(${PANNICC} -O0 --passes=${PARAMS} ${test} > ${OUTPUT_DIR}/${INPUT}_select.lir)
    fi
done

exit 0
