#!/bin/bash

# TODO: unhardcode PANNICC_DIR
PANNICC_DIR="${HOME}/code/projects/PANNICC"

PANNICC="${PANNICC_DIR}/install/bin/pannicc"
INPUT_DIR="${PANNICC_DIR}/test/regression/input"
OUTPUT_DIR="${PANNICC_DIR}/test/regression/expected"

for test in ${INPUT_DIR}/*.c; do
    base_name=$(basename ${test})
    echo "Updating output for ${base_name}..."

    input="${base_name%.c}"

    ${PANNICC} -O0 -E ${test} -o ${OUTPUT_DIR}/${input}_p.c
    ${PANNICC} -O0 --emit-ast ${test} -o ${OUTPUT_DIR}/${input}.ast
    ${PANNICC} -O0 --emit-hir ${test} -o ${OUTPUT_DIR}/${input}.hir

    for opt in "0" "1"; do
        output_base=${OUTPUT_DIR}/${input}_o${opt}
        ${PANNICC} -O${opt} --emit-mir ${test} -o ${output_base}.mir
        ${PANNICC} -O${opt} --emit-lir-isel ${test} -o ${output_base}_isel.lir
        ${PANNICC} -O${opt} --emit-lir-regalloc ${test} -o ${output_base}_regalloc.lir
        ${PANNICC} -O${opt} -S ${test} -o ${output_base}.s
    done

    passes=${INPUT_DIR}/${input}.passes
    if [ -e ${passes} ]; then
        params=$(paste -sd, ${passes})
        opt="-O0 --passes=${params}"

        output_base=${OUTPUT_DIR}/${input}_s
        ${PANNICC} ${opt} --emit-mir ${test} -o ${output_base}.mir
        ${PANNICC} ${opt} --emit-lir-isel ${test} -o ${output_base}_isel.lir
        ${PANNICC} ${opt} --emit-lir-regalloc ${test} -o ${output_base}_regalloc.lir
        ${PANNICC} ${opt} -S ${test} -o ${output_base}.s
    fi
done

exit 0
