#!/bin/bash

PANNICC_DIR="${HOME}/code/projects/PANNICC"

PANNICC="${PANNICC_DIR}/debug/bin/pannicc"
INPUT_DIR="${PANNICC_DIR}/test/regression/input"
OUTPUT_DIR="${PANNICC_DIR}/test/regression/expected"

for test in ${INPUT_DIR}/*.c; do
    BASE_NAME=$(basename ${test})
    echo "Updating output for ${BASE_NAME}..."

    INPUT="${BASE_NAME%.c}"

    $(${PANNICC} --dump-ast ${test} > ${OUTPUT_DIR}/${INPUT}.ast)
    $(${PANNICC} --dump-hir ${test} > ${OUTPUT_DIR}/${INPUT}.hir)
    $(${PANNICC} -O0 ${test} > ${OUTPUT_DIR}/${INPUT}.mir)

    PASSES=${INPUT_DIR}/${INPUT}.passes 
    if [ -e ${PASSES} ]; then
        PARAMS=$(paste -sd, ${PASSES})
        $(${PANNICC} -O0 --passes=${PARAMS} ${test} > ${OUTPUT_DIR}/${INPUT}_opt.mir)
    fi

    # TODO: generate tests with passes
done

exit 0
